import asyncio
import os
import uuid
from datetime import datetime, timedelta
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

async def populate():
    load_dotenv()
    uri = os.getenv("MONGODB_URI")
    db_name = os.getenv("MONGODB_DB_NAME")
    client = AsyncIOMotorClient(uri)
    db = client[db_name]
    col = db['medications']

    vendor_ids = ["69947d80f7f198a8f13efebf", "69905d49c857901ed124f37b"]
    vertical_id = "69b564ef7c13f839ae78e0ba"

    # Delete ALL existing data first as requested to avoid schema conflicts
    await col.delete_many({})
    print("Cleared all existing medications.")

    medicines_data = [
        {
            "name": "Amoxyclav 625",
            "brand_name": "Clavam Forte",
            "generic_composition": "Amoxicillin + Clavulanate",
            "category": "Antibiotic",
            "dosage_form": "Tablet",
            "strength": "625 mg",
            "species": "Both",
            "is_prescription_required": True,
            "indications": "Bacterial infections",
            "contraindications": "Penicillin allergy",
            "side_effects": "Diarrhea, Nausea",
            "storage_instructions": "Store in a cool dry place",
            "quantity_to_give": "1 Strip (10 tabs)",
            "unit": "Strip",
            "base_price": 150.0,
            "purchase_price": 100.0,
            "selling_price": 150.0,
            "manufacturer": "Alkem Laboratories",
            "supplier_name": "VetMed Wholesale",
            "pack_size": "10 tablets per strip",
            "units_per_pack": 10,
            "reorder_level": 20,
            "reorder_quantity": 50,
            "location": "Shelf A1",
        },
        {
            "name": "Melonex Oral Suspension",
            "brand_name": "Melonex",
            "generic_composition": "Meloxicam",
            "category": "NSAID",
            "dosage_form": "Syrup",
            "strength": "1.5 mg/ml",
            "species": "Dog",
            "is_prescription_required": True,
            "indications": "Pain and inflammation",
            "contraindications": "Kidney disease",
            "side_effects": "Vomiting, loss of appetite",
            "storage_instructions": "Protect from light",
            "quantity_to_give": "1 Bottle (10 ml)",
            "unit": "Bottle",
            "base_price": 85.0,
            "purchase_price": 60.0,
            "selling_price": 85.0,
            "manufacturer": "Intas Pharmaceuticals",
            "supplier_name": "PetCare Distributors",
            "pack_size": "10 ml bottle",
            "units_per_pack": 1,
            "reorder_level": 15,
            "reorder_quantity": 30,
            "location": "Shelf B2",
        },
        {
            "name": "Bravecto Chewable",
            "brand_name": "Bravecto",
            "generic_composition": "Fluralaner",
            "category": "Dewormer",
            "dosage_form": "Chewable",
            "strength": "250 mg",
            "species": "Dog",
            "is_prescription_required": False,
            "indications": "Tick and flea prevention",
            "contraindications": "History of seizures",
            "side_effects": "Lethargy",
            "storage_instructions": "Room temperature",
            "quantity_to_give": "1 Chew",
            "unit": "Pcs",
            "base_price": 1200.0,
            "purchase_price": 950.0,
            "selling_price": 1200.0,
            "manufacturer": "MSD Animal Health",
            "supplier_name": "Direct Pharma",
            "pack_size": "1 chew per box",
            "units_per_pack": 1,
            "reorder_level": 10,
            "reorder_quantity": 20,
            "location": "Shelf C1",
        },
        {
            "name": "Savavet Cephavet 300",
            "brand_name": "Cephavet",
            "generic_composition": "Cephalexin",
            "category": "Antibiotic",
            "dosage_form": "Tablet",
            "strength": "300 mg",
            "species": "Both",
            "is_prescription_required": True,
            "indications": "Skin and soft tissue infections",
            "quantity_to_give": "1 Strip (10 tabs)",
            "unit": "Strip",
            "base_price": 220.0,
            "purchase_price": 170.0,
            "selling_price": 220.0,
            "manufacturer": "Sava Vet",
            "supplier_name": "VetMed Wholesale",
            "pack_size": "10 tablets per strip",
            "units_per_pack": 10,
            "reorder_level": 25,
            "reorder_quantity": 50,
            "location": "Shelf A2",
        },
        {
            "name": "Wiggles Wokazole Lotion",
            "brand_name": "Wokazole",
            "generic_composition": "Ofloxacin + Ornidazole + Itraconazole",
            "category": "Antifungal",
            "dosage_form": "Lotion",
            "strength": "50 ml",
            "species": "Both",
            "is_prescription_required": False,
            "indications": "Skin infections",
            "quantity_to_give": "1 Bottle",
            "unit": "Bottle",
            "base_price": 350.0,
            "purchase_price": 280.0,
            "selling_price": 350.0,
            "manufacturer": "Wiggles",
            "supplier_name": "PetCare Distributors",
            "pack_size": "50 ml bottle",
            "units_per_pack": 1,
            "reorder_level": 12,
            "reorder_quantity": 24,
            "location": "Shelf D1",
        },
        {
            "name": "Carodyl 100",
            "brand_name": "Carodyl",
            "generic_composition": "Carprofen",
            "category": "NSAID",
            "dosage_form": "Tablet",
            "strength": "100 mg",
            "species": "Dog",
            "is_prescription_required": True,
            "indications": "Osteoarthritis pain",
            "quantity_to_give": "1 Strip (6 tabs)",
            "unit": "Strip",
            "base_price": 450.0,
            "purchase_price": 350.0,
            "selling_price": 450.0,
            "manufacturer": "Sava Vet",
            "supplier_name": "VetMed Wholesale",
            "pack_size": "6 tablets per strip",
            "units_per_pack": 6,
            "reorder_level": 30,
            "reorder_quantity": 60,
            "location": "Shelf B1",
        },
        {
            "name": "Stoppa Diarrhea Syrup",
            "brand_name": "Stoppa",
            "generic_composition": "Metronidazole + Norfloxacin",
            "category": "Antidiarrheal",
            "dosage_form": "Syrup",
            "strength": "30 ml",
            "species": "Both",
            "is_prescription_required": True,
            "indications": "Gastro-intestinal infections",
            "quantity_to_give": "1 Bottle",
            "unit": "Bottle",
            "base_price": 120.0,
            "purchase_price": 90.0,
            "selling_price": 120.0,
            "manufacturer": "SkyEc",
            "supplier_name": "Direct Pharma",
            "pack_size": "30 ml bottle",
            "units_per_pack": 1,
            "reorder_level": 20,
            "reorder_quantity": 40,
            "location": "Shelf B3",
        },
        {
            "name": "Himalaya Liv.52 Pet Syrup",
            "brand_name": "Liv.52 Pet",
            "generic_composition": "Herbal Liver Supplement",
            "category": "Supplement",
            "dosage_form": "Syrup",
            "strength": "200 ml",
            "species": "Both",
            "is_prescription_required": False,
            "indications": "Liver disorders, appetite stimulant",
            "quantity_to_give": "1 Bottle",
            "unit": "Bottle",
            "base_price": 180.0,
            "purchase_price": 140.0,
            "selling_price": 180.0,
            "manufacturer": "Himalaya Wellness",
            "supplier_name": "Himalaya Direct",
            "pack_size": "200 ml bottle",
            "units_per_pack": 1,
            "reorder_level": 50,
            "reorder_quantity": 100,
            "location": "Shelf E1",
        },
        {
            "name": "Preditabs 5mg",
            "brand_name": "Preditabs",
            "generic_composition": "Prednisolone",
            "category": "Corticosteroid",
            "dosage_form": "Tablet",
            "strength": "5 mg",
            "species": "Both",
            "is_prescription_required": True,
            "indications": "Allergic conditions, inflammation",
            "quantity_to_give": "1 Strip (10 tabs)",
            "unit": "Strip",
            "base_price": 45.0,
            "purchase_price": 30.0,
            "selling_price": 45.0,
            "manufacturer": "Sava Vet",
            "supplier_name": "VetMed Wholesale",
            "pack_size": "10 tablets per strip",
            "units_per_pack": 10,
            "reorder_level": 100,
            "reorder_quantity": 200,
            "location": "Shelf A3",
        },
        {
            "name": "Otiblast Ear Drops",
            "brand_name": "Otiblast",
            "generic_composition": "Ofloxacin + Clotrimazole + Betamethasone",
            "category": "Ear Care",
            "dosage_form": "Drops",
            "strength": "15 ml",
            "species": "Both",
            "is_prescription_required": True,
            "indications": "Ear infections",
            "quantity_to_give": "1 Bottle",
            "unit": "Bottle",
            "base_price": 165.0,
            "purchase_price": 125.0,
            "selling_price": 165.0,
            "manufacturer": "SkyEc",
            "supplier_name": "PetCare Distributors",
            "pack_size": "15 ml bottle",
            "units_per_pack": 1,
            "reorder_level": 25,
            "reorder_quantity": 50,
            "location": "Shelf D2",
        },
        {
            "name": "Vetade multivitamin",
            "brand_name": "Vetade",
            "generic_composition": "Vitamins A, D3, E",
            "category": "Supplement",
            "dosage_form": "Injection",
            "strength": "10 ml",
            "species": "Both",
            "is_prescription_required": True,
            "indications": "Vitamin deficiency",
            "quantity_to_give": "1 Vial",
            "unit": "Vial",
            "base_price": 75.0,
            "purchase_price": 55.0,
            "selling_price": 75.0,
            "manufacturer": "Concept Pharma",
            "supplier_name": "Direct Pharma",
            "pack_size": "10 ml vial",
            "units_per_pack": 1,
            "reorder_level": 20,
            "reorder_quantity": 40,
            "location": "Fridge",
        },
        {
            "name": "Ceftriaxone 1g Injection",
            "brand_name": "Intacef",
            "generic_composition": "Ceftriaxone",
            "category": "Antibiotic",
            "dosage_form": "Injection",
            "strength": "1 g",
            "species": "Both",
            "is_prescription_required": True,
            "indications": "Severe bacterial infections",
            "quantity_to_give": "1 Vial",
            "unit": "Vial",
            "base_price": 130.0,
            "purchase_price": 95.0,
            "selling_price": 130.0,
            "manufacturer": "Intas Pharmaceuticals",
            "supplier_name": "VetMed Wholesale",
            "pack_size": "1 vial",
            "units_per_pack": 1,
            "reorder_level": 40,
            "reorder_quantity": 80,
            "location": "Shelf A4",
        }
    ]

    total_inserted = 0
    now = datetime.utcnow()

    for vid in vendor_ids:
        print(f"Adding data for vendor: {vid}")
        for med in medicines_data:
            doc = med.copy()
            med_id = f"MED-{uuid.uuid4().hex[:8].upper()}"
            doc.update({
                "medicine_id": med_id,
                "vendor_id": vid,
                "vertical_id": vertical_id,
                "batch_id": f"BAT-{uuid.uuid4().hex[:6].upper()}",
                "stock_quantity": 100,
                "mfd_date": (now - timedelta(days=90)).strftime("%Y-%m-%d"),
                "expiry_date": (now + timedelta(days=365)).strftime("%Y-%m-%d"),
                "last_restocked_date": (now - timedelta(days=5)).strftime("%Y-%m-%d"),
                "is_active": True,
                "status": "Active",
                "is_expired": False,
                "image_url": f"https://doffairimages-daeueyayhqfxf0gv.z02.azurefd.net/dev-images/med-{uuid.uuid4().hex[:6]}.jpg",
                "created_at": now,
                "updated_at": now,
                "notes": "System generated for testing",
                "near_expiry_flag": False,
                "barcode": f"890{uuid.uuid4().hex[:10].upper()}",
                "qr_code": f"QR-{uuid.uuid4().hex[:8].upper()}",
                "supplier_contact": "+91-9876543210",
                "duration": "As directed",
                "frequency": "Once daily",
                "dosage": med.get("strength")
            })
            await col.insert_one(doc)
            total_inserted += 1

    print(f"Finished! Total inserted: {total_inserted}")

if __name__ == "__main__":
    asyncio.run(populate())
